### ISSUE TITLE
Image manager url bug

### ISSUE THREAD

**Issue by ghost** [widgetfactory/jce#47]
There are no parameter to hide url line in Image manager
![jce](https://user-images.githubusercontent.com/43875462/58870897-b3869180-86c9-11e9-97d1-5f3304910f00.png)

How can we not display this line in red ?

**Comment by ryandemmer** [comment]
This is not currently possible.

I might add this as an option JCE 2.8

**Comment by ghost** [comment]
Thanks Ryan it would be great, now this is very confusig to our users
Is it posible to get this as an option in JCE 2.7.14 ?

**Comment by ryandemmer** [comment]
> Is it posible to get this as an option in JCE 2.7.14 ?

No, 2.7.14 is ready for release tomorrow and no new features are being added (this is not a bug)

**Comment by ghost** [comment]
Ryan, maybe you know what file we need to edit to not display this line in red ? while waiting for JCE 2.8

**Comment by ryandemmer** [comment]
Add a file called **plugin.css** in **/media/jce/css/** containing the following:

```css
[data-plugin="imgmanager"] #src {
    display: none;
}
```

**Comment by ryandemmer** [comment]
Or better yet:
```css
[data-plugin="imgmanager"] #image_tab > div > div > div:first-child {
	display: none;
}
```
